# Generated by Django 5.1.4 on 2024-12-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=50, verbose_name='Врач')),
                ('patient', models.CharField(max_length=50, verbose_name='Пациент')),
                ('diagnos', models.TextField(verbose_name='Диагноз')),
                ('date', models.DateTimeField(verbose_name='Дата записи')),
            ],
        ),
    ]
